final products = [
  {
    'id': 0,
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': 1,
    'title': 'Adidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoes_2.png',
    'comapny': 'Adidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': 2,
    'title': 'Bata Women\'s Nike Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': 3,
    'title': 'Jordan Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 4,
    'title': 'Men\'s Nike Shoes',
    'price': 40.69,
    'imageUrl': 'assets/images/nike-shoes-1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 5,
    'title': 'Jordan Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/jordan-1.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 6,
    'title': 'Jordan Shoes',
    'price': 32.69,
    'imageUrl': 'assets/images/jordan-2.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 7,
    'title': 'Men\'s Nike Shoes',
    'price': 32.69,
    'imageUrl': 'assets/images/nike-shoes-2.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 8,
    'title': 'Adidas Shoes',
    'price': 46.29,
    'imageUrl': 'assets/images/adidas-shoes-4.jpg',
    'company': 'Adidas',
    'sizes': [8, 9, 10],
  },
  {
    'id': 9,
    'title': 'Jordan Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/jordan-3.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 10,
    'title': 'Adidas Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/adidas-shoes-3.jpg',
    'company': 'Adidas',
    'sizes': [8, 9, 10],
  },
  {
    'id': 11,
    'title': 'Men\'s Nike Shoes',
    'price': 45.99,
    'imageUrl': 'assets/images/nike-shoes-4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 12,
    'title': 'Jordan Shoes',
    'price': 52.69,
    'imageUrl': 'assets/images/jordan-4.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 13,
    'title': 'Bata Women\'s Nike Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/bata-3.jpg',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': 14,
    'title': 'Men\'s Nike Shoes',
    'price': 36.49,
    'imageUrl': 'assets/images/nike-shoes-4.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 15,
    'title': 'Bata Women\'s Nike Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/bata-2.jpg',
    'company': 'Bata',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': 16,
    'title': 'Bata Women\'s Nike Shoes',
    'price': 42.69,
    'imageUrl': 'assets/images/bata-1.jpg',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': 17,
    'title': 'Adidas Shoes',
    'price': 47.69,
    'imageUrl': 'assets/images/adidas-shoes-2.jpg',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': 18,
    'title': 'Adidas Shoes',
    'price': 22.69,
    'imageUrl': 'assets/images/adidas-shoes-1.jpg',
    'company': 'Adidas',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': 19,
    'title': 'Bata Women\'s Nike Shoes',
    'price': 43.69,
    'imageUrl': 'assets/images/bata-4.jpg',
    'company': 'Bata',
    'sizes': [8, 9, 10, 11],
  },
];

final cart = [
  {
    'id': 3,
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'size': 8,
  }
];
